FROM node:20-alpine as test

WORKDIR /usr/src/app

COPY package*.json tsconfig.json tsconfig.spec.json ./

ENV NODE_ENV=TEST

RUN npm install 

COPY ./ ./

RUN npm run build

CMD ["npm", "run", "test"]

