import LayoutProvider from "@/lib/provider/LayoutProvider";
import { SWRProvider } from "@/lib/provider/SwrProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Menu from "@/containers/menu/page";
import Right from "@/containers/right/page";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ER",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // 초기 테마를 설정하는 함수

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <SWRProvider>
          <div className="flex">
            <Menu />
            {/* <AuthProvider> */}
            <LayoutProvider>{children}</LayoutProvider>
            {/* </AuthProvider> */}
            <Right />
          </div>
        </SWRProvider>
      </body>
    </html>
  );
}
